/* FP KR 번역 맵 — 영어 평문(태그·이모지 제거) → 한국어 */
window.LIO_KR_MAP = {
  'What is "A Day at the Tide Pools" mostly about?': '"조수 웅덩이의 하루"는 주로 무엇에 관한 이야기인가요?',
  'a girl who discovers the animals and wonders of tide pools': '조수 웅덩이의 동물과 신비로움을 발견하는 소녀',
  'a girl who learns how to swim in the ocean with her class': '반 친구들과 바다에서 수영을 배우는 소녀',
  'a class that finds a lost sea star on a rocky beach': '바위 해변에서 잃어버린 불가사리를 찾는 학급',
  'a teacher who studies ocean water for a science project': '과학 프로젝트를 위해 바닷물을 연구하는 선생님',
  'Find the topic or main character': '주제나 주인공을 찾으세요',
  'Find the key details': '핵심 세부 내용을 찾으세요',
  'Ask "What big idea covers ALL the key details?" — that is the main idea.': '"모든 핵심 내용을 아우르는 큰 생각은 무엇일까?"라고 물어보세요 — 그것이 주제입니다.',
  'Read the passage and answer the question.': '지문을 읽고 질문에 답하세요.',
  'If you want to listen, press the Listen button next to each paragraph.': '듣고 싶으면 각 단락 옆 Listen 버튼을 누르세요.',
  "You did great! You found the main idea about the girl's discovery at the tide pools. Let's move on to the next step!": '잘했어요! 소녀가 조수 웅덩이에서 발견한 내용의 주제를 찾았네요. 다음 단계로 가 볼까요!',
  "Nice work! Choose what you'd like to do next.": '잘했어요! 다음에 무엇을 할지 골라 보세요.',
  'Evidence Tap': '근거 찾기(Evidence Tap)',
  'Now, tap the sentence in the passage that best supports the main idea.': '이제 주제를 가장 잘 뒷받침하는 문장을 지문에서 탭하세요.',
  "You're ready to dive into Evidence Tap. Let's explore together!": '이제 Evidence Tap을 시작할 준비가 됐어요. 함께 탐험해 봐요!',
  'Great work! You found where Maya discovered tide pools. The evidence strongly supports the main idea about her exploration.': '잘했어요! Maya가 조수 웅덩이를 발견한 부분을 찾았네요. 이 근거는 탐험에 대한 주제를 잘 뒷받침해요.',
  "Great job working through that on your own! Here's the strategy you just used — save it for next time.": '혼자 해내다니 정말 잘했어요! 방금 쓴 전략이에요 — 다음에도 기억해 두세요.',
  "Great job working through that on your own! Here's the strategy you just used—save it for next time.": '혼자 해내다니 정말 잘했어요! 방금 쓴 전략이에요 — 다음에도 기억해 두세요.',
  "You're ready to dive into Evidence Tap!": '이제 Evidence Tap을 시작할 준비가 됐어요!',
  'Try looking where Maya visits and discovers new things. Try again. Tap the sentence that best supports the main idea.': 'Maya가 방문하고 새로운 것을 발견하는 부분을 찾아보세요. 다시 시도해 봐요. 주제를 가장 잘 뒷받침하는 문장을 탭하세요.',
  "Not quite, but good try! The evidence is highlighted in the passage. It shows how Maya's visit helped her discover many wonders in the tide pools.": '아쉽지만 좋은 시도예요! 근거가 지문에 하이라이트되어 있어요. Maya의 방문이 조수 웅덩이의 많은 신비를 발견하는 데 어떻게 도움이 됐는지 보여 줘요.',
  'Read the question and pick your answer.': '질문을 읽고 답을 고르세요.',
  "No worries, mistakes help us learn! Let's see why this answer might not fit.": '괜찮아요, 실수는 배우는 데 도움이 돼요! 이 답이 왜 맞지 않는지 살펴볼게요.',
  'Pick why this answer is wrong.': '이 답이 틀린 이유를 고르세요.',
  'Not in the text': '지문에 없음',
  'Opposite meaning to what the text says': '지문이 말하는 것과 반대 의미',
  'Too specific or too general (only one detail, or too broad)': '너무 구체적이거나 너무 일반적임 (세부 하나만, 또는 너무 넓음)',
  'Not what the question asks for': '질문이 묻는 것이 아님',
  "The correct reason is 'Too specific or too general'. The passage does not mention Maya learning to swim — it only talks about exploring.": "정답 이유는 '너무 구체적이거나 너무 일반적임'이에요. 지문은 Maya가 수영을 배운다는 말은 없고, 탐험에 대해서만 말해요.",
  "Now we know why it didn't fit — let's practice and try again! What would you like to do first?": '왜 안 맞았는지 알았으니 — 연습하고 다시 도전해 봐요! 무엇을 먼저 할까요?',
  'Can I check some words?': '단어를 좀 확인할 수 있을까요?',
  'Let me practice the skill!': '스킬을 연습할게요!',
  'Something else': '다른 것',
  "Let's warm up with a couple of key words!": '핵심 단어 몇 개로 워밍업해 볼까요!',
  'Word Check': '단어 확인',
  "Let's see how well you know these words!": '이 단어들을 얼마나 잘 아는지 볼까요!',
  "What does 'amazed' mean?": "'amazed'는 무슨 뜻일까요?",
  'very surprised': '매우 놀란',
  'very sad': '매우 슬픈',
  'very angry': '매우 화난',
  'very happy': '매우 행복한',
  "Great! 'Amazed' means very surprised, just like in the passage 'A Day at the Tide Pools'.": "잘했어요! 'Amazed'는 매우 놀랐다는 뜻이에요. 지문 '조수 웅덩이의 하루'에서처럼요.",
  'What does "spotted" mean?': '"spotted"는 무슨 뜻일까요?',
  'Saw or noticed': '보거나 알아챔',
  'Painted or colored': '칠하거나 색을 입힘',
  'Walked or ran quickly': '빨리 걷거나 달림',
  'Rain fell heavily': '비가 세차게 내림',
  'X does not mean that. "Spotted" means saw or noticed.': '그건 아니에요. "Spotted"는 보거나 알아챘다는 뜻이에요.',
  "Let's practice the skill! How would you like to start?": '스킬을 연습해 볼까요! 어떻게 시작하고 싶어요?',
  "Let's read and check what I understood!": '읽고 내가 이해한 것을 확인해 볼게요!',
  'Explain the story to me!': '이야기를 설명해 주세요!',
  "Great! Let's read each paragraph together.": '좋아요! 각 단락을 함께 읽어 봐요.',
  "Let's read paragraph 1! Use the listen button in the passage.": '1단락을 읽어 봐요! 지문의 Listen 버튼을 사용하세요.',
  'Where did Maya explore?': 'Maya는 어디에서 탐험했나요?',
  'The rocky shore': '바위 해안',
  'The sandy beach': '모래 해변',
  'Yes! Great job!': '맞아요! 잘했어요!',
  'Great reading! You know all 4 paragraphs.': '잘 읽었어요! 4단락을 모두 알았네요.',
  "Now, you're going to practice the Main Idea skill. This skill is about finding the ONE big idea that covers the WHOLE passage — not just one paragraph!": '이제 주제(Main Idea) 스킬을 연습할 거예요. 이 스킬은 한 단락이 아니라 지문 전체를 아우르는 하나의 큰 생각을 찾는 것이에요!',
  'Maya went to the ocean that summer. Her class explored the tide pools together. Tide pools are small water pools left by the ocean. Maya saw them for the first time. They walked on the rocky shore.': '그해 여름 Maya는 바다에 갔어요. 반 친구들과 함께 조수 웅덩이를 탐험했죠. 조수 웅덩이는 바닷물이 빠지며 남는 작은 물웅덩이예요. Maya는 처음 봤어요. 그들은 바위 해안을 걸었어요.',
  'Maya saw little ocean pools for the first time.': 'Maya는 작은 바다 웅덩이를 처음 봤어요.',
  'This passage is about exploring tide pools. Do you like exploring new places?': '이 지문은 조수 웅덩이 탐험에 관한 이야기예요. 새로운 장소를 탐험하는 걸 좋아하나요?',
  'Yes, I do!': '네, 좋아해요!',
  'Yes, I do! 🌊': '네, 좋아해요! 🌊',
  'Not really… 😊': '별로… 😊',
  'I want to tell you more! ✏️': '더 말하고 싶어요! ✏️',
  'Exploring places is exciting and fun! Keep being curious about the world.': '장소를 탐험하는 건 신나고 재미있어요! 세상에 대한 호기심을 계속 가져 봐요.',
  "Okay! Let's start the skill practice!": '좋아요! 스킬 연습을 시작해 볼까요!',
  'Let us look at our question: What is A Day at the Tide Pools mostly about?': '질문을 볼까요: "조수 웅덩이의 하루"는 주로 무엇에 관한 이야기인가요?',
  'What is the question asking you to find?': '질문이 찾으라고 하는 것은 무엇인가요?',
  'the main idea': '주제(main idea)',
  'one specific fact': '하나의 구체적 사실',
  'a cause and effect': '원인과 결과',
  'how things are different': '어떻게 다른지',
  'Keep trying, Sumin. Correct: A - main idea. Mostly about asks for idea covering ALL paragraphs.': '계속해 봐요, Sumin. 정답: A - 주제. "mostly about"는 모든 단락을 아우르는 생각을 묻죠.',
  'Select three key details about what Maya did and discovered.': 'Maya가 하고 발견한 것에 대한 핵심 세부 내용 세 가지를 고르세요.',
  'Select 3 details that show what Maya did.': 'Maya가 한 일을 보여 주는 세부 내용 3개를 고르세요.',
  'Maya and her class visited the tide pools for exploration.': 'Maya와 반은 탐험을 위해 조수 웅덩이를 방문했어요.',
  'She learned even small pools have many living things.': '작은 웅덩이에도 많은 생물이 있다는 걸 배웠어요.',
  'Maya learned how to swim in the tide pools.': 'Maya는 조수 웅덩이에서 수영하는 법을 배웠어요.',
  'Almost there! Remember, Maya did not learn swimming. Correct details: explored tide pools, living things in pools, learned even small pools have many creatures.': '거의 다 왔어요! Maya는 수영을 배우지 않았어요. 맞는 세부: 조수 웅덩이 탐험, 웅덩이 속 생물, 작은 웅덩이에도 많은 생물이 있다는 사실.',
  'Tap one of the evidence sentences that answers the question.': '질문에 답하는 근거 문장 중 하나를 탭하세요.',
  'That sentence is a detail — look for a sentence that connects directly to what Maya saw or learned overall.': '그 문장은 세부 내용이에요 — Maya가 전체적으로 보거나 배운 것과 바로 연결되는 문장을 찾으세요.',
  "Yes! That's one of the evidence sentences! It directly supports the main idea — Maya's discovery of tide pools.": '맞아요! 근거 문장 중 하나예요! Maya의 조수 웅덩이 발견이라는 주제를 직접 뒷받침해요.',
  'Here are the evidence sentences highlighted in green! Each one shows what Maya discovered or learned.': '초록색으로 하이라이트된 근거 문장들이에요! 각각 Maya가 발견하거나 배운 것을 보여 줘요.',
  "Do you have anything you don't understand? Tap the sentence.": '모르는 부분이 있나요? 문장을 탭하세요.',
  "Yes, I'll tap it. 👆": '네, 탭할게요. 👆',
  "No, let's move on! ▶": '아니요, 다음으로! ▶',
  'A hermit crab moves with its borrowed shell on the sand.': '소라게가 빌린 껍데기를 달고 모래 위를 움직여요.',
  'Before we try the question again — do you have anything you want to ask?': '질문을 다시 풀기 전에 — 묻고 싶은 게 있나요?',
  'Yes, I have a question! 💬': '네, 질문이 있어요! 💬',
  "No, let's go! ▶": '아니요, 가요! ▶',
  'Choose the best answer.': '가장 좋은 답을 고르세요.',
  "Not quite, but you got this! The correct answer is: a girl who discovers the animals and wonders of tide pools, because it covers all about Maya's experiences and observations.": '아쉽지만 할 수 있어요! 정답은: 조수 웅덩이의 동물과 신비로움을 발견하는 소녀예요. Maya의 경험과 관찰 전체를 아우르거든요.',
  'You finished the Skill Practice! Great work today!': '스킬 연습을 끝냈어요! 오늘 정말 잘했어요!',
  "Let's talk! 💬": '이야기해요! 💬',
  "I'm done! 👋": '끝났어요! 👋',
  'You said that you like new places. Where do you want to explore next?': '새로운 장소를 좋아한다고 했지요. 다음에 어디를 탐험하고 싶어요?',
  "Nice, you're talking about a country!": '오, 나라에 대해 말하고 있네요!',
  "Now it's your turn! You can ask ME anything — you can even ask in Korean! Click my face moving around the screen!": '이제 네 차례야! 나에게 뭐든지 물어봐 — 한국어로도 괜찮아! 화면을 돌아다니는 내 얼굴을 클릭해 봐!',
  "Now it's your turn! You can ask ME anything — you can even ask in Korean!": '이제 네 차례야! 나에게 뭐든지 물어봐 — 한국어로도 괜찮아!',
  'This was so much fun! You did great today. See you next time! 👋': '정말 재미있었어! 오늘 잘했어. 다음에 또 만나!',
  'You did great! You found the main idea about the tide pools.': '잘했어요! 조수 웅덩이에 대한 주제를 찾았네요.',
  "I'm ready! Let's go!": '준비됐어요! 가요!',
  'I want to check some words.': '단어를 확인하고 싶어요.',
  'Walk me through the passage.': '지문을 함께 읽어 주세요.',
  'I need something else.': '다른 게 필요해요.',
  'Tap any blue or dotted word! When you are ready, press Continue.': '파란색이나 점선 단어를 탭해 보세요! 준비가 되면 Continue를 누르세요.',
  'Before we start, you can tap any blue or dotted word in the passage to check its meaning! Want to check words or go straight to walking through the passage?': '시작하기 전에 지문의 파란/점선 단어를 탭해 뜻을 확인할 수 있어요! 단어를 볼까요, 바로 지문 읽기로 갈까요?',
  'Let me check words first! 📖': '먼저 단어를 확인할래요! 📖',
  "I'm ready to listen! 👂": '들을 준비됐어요! 👂',
  'Paragraph 1 introduces Maya and her class trip. Maya visits the ocean to explore tide pools for the first time.': '1단락은 Maya와 학급 여행을 소개해요. Maya는 조수 웅덩이를 처음 탐험하러 바다에 가요.',
  'Type or talk to me — tell me what you need! If English is hard, you can write in Korean too.': '타이핑하거나 말해 주세요 — 필요한 걸 알려 줘요! 영어가 어려우면 한국어로 써도 돼요.',
  "Maya discovered amazing things at the tide pools! Let's see what the key words are or walk through the passage together.": 'Maya는 조수 웅덩이에서 놀라운 것들을 발견했어요! 핵심 단어를 보거나 지문을 함께 읽어 볼까요.',
  "That's not quite the main focus. Look near the start of her trip. Try again. Tap the sentence that best supports the main idea.": '그게 핵심은 아니에요. 여행 시작 부분을 보세요. 다시 시도해 봐요. 주제를 가장 잘 뒷받침하는 문장을 탭하세요.',
  "Great choice! The evidence shows Maya's discoveries in the tide pools connect perfectly with the main idea of discovering animals and wonders.": '좋은 선택이에요! 근거는 Maya의 조수 웅덩이 발견이 동물과 신비로움을 발견한다는 주제와 잘 연결됨을 보여 줘요.',
  "Great job! You found the right details. You connected Maya's visit to finding living things.": '잘했어요! 맞는 세부 내용을 찾았네요. Maya의 방문과 생물을 발견한 것을 연결했어요.',
  'Got it! 👍': '알겠어요! 👍',
  'More simply 🔁': '더 쉽게 🔁',
  'Okay! ✅': '좋아요! ✅',
  'Next paragraph ▶': '다음 단락 ▶',
  'I have a question 🙋': '질문이 있어요 🙋',
  'Continue ▶': '계속 ▶',
  'Next ▶': '다음 ▶',
  "I'm done! Let's go ▶": '끝났어요! 가요 ▶',
  "Let's read! ▶": '읽어요! ▶',
  'Start Skill Practice! ▶': '스킬 연습 시작! ▶',
  'Check ✓': '확인 ✓',
  'Another sentence? 👆': '다른 문장? 👆',
  "Let's move on! ▶": '다음으로! ▶',
  'amazed': 'amazed (매우 놀란)',
  'spotted': 'spotted (보거나 알아챔)',
  'Walk the Passage': '지문 함께 읽기',
  'S1 — Question Type': 'S1 — 질문 유형',
  'S2 — Key Details': 'S2 — 핵심 세부',
  'S4 — Find the Evidence': 'S4 — 근거 찾기',
  'Retry — Main Question': '다시 풀기 — 메인 질문',
  'Paragraph 1': '1단락',
  '… Paragraph 1~4 반복 후 …': '… 1~4단락 반복 후 …',
  '… 4단락 반복 …': '… 4단락 반복 …',
  '…land': '…나라',
  '🎉 All done! 오늘 학습 끝!': '🎉 모두 끝! 오늘 학습 끝!',
  '🎉 Further Practice 2 Complete!': '🎉 Further Practice 2 완료!',
  "👆 Tap a sentence in the passage above!": '👆 위 지문에서 문장을 탭하세요!',
  "It looks like some words need a little more practice — let's do some word learning together! (1/2)This sample ends at the Word Check. Next step would be: 단어 학습 활동(Word Activity)": '몇몇 단어는 조금 더 연습이 필요해 보여요 — 함께 단어 학습을 해 볼까요! (1/2) 이 샘플은 Word Check에서 끝나요. 다음은 단어 학습 활동입니다.',
  'Tap a word! 👆': '단어를 탭하세요! 👆',
  "Maya는 무엇을 했어?": 'Maya는 무엇을 했어?',
};
